### ISSUE TITLE
Typo in Program.cs

### ISSUE THREAD

**Issue by Itsnotjames** [KennyFour20/ConsoleQuest#1]
Basically is miss-pelt as "basicaly" at line 53.
https://github.com/KennyFour20/ConsoleQuest/blob/8c1b31e971f03e2d5963867bd4c847cadc966023/ConsoleQuest/Program.cs#L53

**Comment by KennyFour20** [comment]
Fuck you and your shit cunt

**Comment by KennyFour20** [comment]
Im da master round these parts

**Comment by KennyFour20** [comment]
ty, Nice guy

**Comment by Itsnotjames** [comment]
o sick u finished it in 356abf75463f8c5293e259464e23c0a5c366d520
